### ISSUE TITLE
Unable to create partners with custom storage space

### ISSUE THREAD

**Issue by MrKoopie** [acronis/acronis-cyber-cloud-whmcs#1]
Since the module does not support the metrics feature (see https://developers.whmcs.com/provisioning-modules/usage-metrics/ ), we sell partner accounts with a set disk space limit. The current implementation of your module does not allow such thing. When I simply comment the following lines, the setup of the accounts works.

Why is this piece of code here? Is there a technical reason for this? Or am I using your implementation incorrectly? The PDF states that the module is designed to not support configurable options for partners, but this is required when you do not support the metrics module.

https://github.com/acronis/acronis-cyber-cloud-whmcs/blob/21cb2515dbf04a19cfca0710dfbb3859398a3850/src/modules/servers/acroniscloud/lib/Controller/Subscription.php#L646-L652

**Comment by Diamond16** [comment]
>Since the module does not support the metrics feature
Please check the latest version, it's already supported starting from build 2.2.0-175
