### ISSUE TITLE
Update repo to v2.2.1-178

### ISSUE THREAD

**Issue by JOEsDC-Seth** [acronis/acronis-cyber-cloud-whmcs#5]
This repository is currently one release behind the module listed on the WHMCS marketplace (v2.2.0-175 instead of v2.2.1-178).  Please update the source code to the newer version if possible. Thanks!

**Comment by JOEsDC-Seth** [comment]
This is probably more info than you need, but the following files will need to be updated to v2.2.1-178:
```
/modules/addons/acroniscloud/assets/admin.js:55
/modules/servers/acroniscloud/assets/client.js:10
/modules/servers/acroniscloud/lib/Controller/Subscription.php:180
/includes/acroniscloud/lib/Model/WHMCS/Upgrade.php:8,30
/includes/acroniscloud/lib/Repository/WHMCS/UpgradeRepository.php:10,12,20,28,37,39,89
```

I temporarily [forked this repo](https://github.com/JOEsDC-Seth/acronis-cyber-cloud-whmcs) in order to recommend some fixes to usage billing, however I thought I should probably wait until the repo is up-to-date before issuing a pull request (all of my testing has been on v2.2.1-178). I have backups of the changes I made and can just delete or rebase my fork once the repo is updated.

**Comment by merx3** [comment]
Hi Seth,

Thanks for the feedback and the input on the fixes. We'll be updating the repo soon and then we'll look into the recommended code changes you suggested for the repo.

Marian

**Comment by JOEsDC-Seth** [comment]
Awesome, thanks!

**Comment by merx3** [comment]
Repo has been updated.
