### ISSUE TITLE
Usage report download_path is problematic

### ISSUE THREAD

**Issue by JOEsDC-Seth** [acronis/acronis-cyber-cloud-whmcs#6]
The behavior of "download_path" in config.yaml is somewhat unclear and potentially insecure. First, it would be difficult to know that download_path must be a sub-folder of the /includes/acroniscloud directory without looking through the code. The "/includes/acroniscloud/tmp/reports" path also does not exist when the module is first installed, so usage metrics will not get updated when the default config.yaml.sample is used.

More importantly, storing usage reports inside a sub-folder of the WHMCS webroot would be an unnecessary risk. These reports are in csv.gz format with a simple directory structure, meaning that it would be trivial for someone to download full Acronis usage details for all clients by simply guessing the path in a web browser. Although this report does not contain high security risk data (such as authentication details), it is certainly info that should not be made publicly accessible.

I propose changing download_path to use an absolute path instead of relative to the includes directory. I have already made this change in a forked repo (see cad9d74054404f84c2268c5cc512b319966e36fb for more info) and verified that it works in a test WHMCS environment. If you have any questions please let me know. At the very least, the includes path should be protected by default with an .htaccess file.

**Comment by merx3** [comment]
Hello Seth,

I agree that the pathing isn't fully clear, and we're aware of related issues to that, so we have a task to update that in a future release. We'll also include some security improvements, such as the ones you suggested. Thanks for your input on the issue.

Marian

**Comment by JOEsDC-Seth** [comment]
Understood, thank you.

**Comment by merx3** [comment]
With build 200, we've moved the location of the reports under the "Downloads" folder that's configured in WHMCS's Storage Settings. That folder must be secured, as per WHMCS guideline

**Comment by JOEsDC-Seth** [comment]
I just wanted to briefly confirm that this did resolve the issue for us. Using the WHMCS "Downloads" path was an excellent choice as well. Thanks again.
