### ISSUE TITLE
Usage totals are incorrect

### ISSUE THREAD

**Issue by JOEsDC-Seth** [acronis/acronis-cyber-cloud-whmcs#8]
It appears that some usage billing metrics are being overwritten when they are imported from csv, causing the usage totals to be incorrect. For example, we have multiple storage locations that we host as an Acronis service provider. When usage is imported for a client, the values from only one of our storage locations is used. Storage locations outside our facility do not have this issue. I believe this is happening because the metrics are getting assigned the same array key during the import, meaning that the last (similar) csv row will be the only one that is kept. To partially address this issue, the imported data can be added instead of overwritten when two similar items are found. This is a simple fix, as illustrated in the following proposed change: 55f55dc437f892c86c72d5021b2f59a8669a26ce

Even with that change however, there is still an issue with how the storage usage is getting calculated. The storage owed by our partners (child storage) is getting counted in exactly the same way as the cloud storage that we host. Partner owned storage is typically priced differently than our storage, so having it be added together (or worse, overwritten) will not work for us. These items need to be split out into the appropriate "Partner Owned Storage" metrics that already exist in the module, instead of getting counted as "Cloud Storage". Any help would be greatly appreciated. Thanks.

**Comment by merx3** [comment]
Hi Seth,

Can I ask, if you could provide us with some additional information, like which plan you used that has issue with totals calculation? You wrote it was for a partner type of subscription, but anything else you can provide as steps/info to reproduce it on our side would be very appreciated.

Best regards,
Marian

**Comment by JOEsDC-Seth** [comment]
We currently host multiple backup storage locations which are accessible to our clients and partners through the Acronis Service Provider program. Some clients also have Acronis storage that they host in their own facility. I will be posting some examples of what the usage would look like for a few hypothetical clients. These are artificial values that I manually populated, however the behavior will be consistent with the data I gathered in testing...

**Comment by JOEsDC-Seth** [comment]
**Example A - 9 TB usage from JDC-KC overwritten by the 0 TB usage from JDC-SF**
From this example, it might appear as though the wrong storage value is being stored since "JDC-SF" is not a location used by this client. Example B will illustrate why both values need to be imported (by adding them together, for example).

Client 1 usage shown on Acronis Cyber Cloud portal and CSV reports

- Totals [Total cloud storage size]: 9208.95 GB
- Totals [Partner-owned backup storage]: 0.00 GB
- Local backup [Local backup]: 210.33 GB
- Cyber Protect [Backup storage (JDC-KC)]: 9208.95 GB
- Cyber Protect [Backup storage (JDC-SF)]: 0.00 GB
- Cyber Backup [Backup storage (JDC-KC)]: 0.00 GB
- Cyber Backup [Backup storage (JDC-SF)]: 0.00 GB

Client 1 usage in WHMCS metrics (from v2.2.1-178 of this module)

- Cyber Protect Cloud - Cloud storage: 0.00 GB
- Cyber Backup Cloud - Cloud storage: 0.00 GB
- Cyber Backup Cloud - Partner storage: 0.00 GB
- Cyber Backup Cloud - Local storage: 0.00 GB

Client 1 usage in WHMCS metrics (generated after fix 55f55dc)

- Cyber Protect Cloud - Cloud storage: 9208.95 GB
- Cyber Backup Cloud - Cloud storage: 0.00 GB
- Cyber Backup Cloud - Partner storage: 0.00 GB
- Cyber Backup Cloud - Local storage: 0.00 GB

**Comment by JOEsDC-Seth** [comment]
**Example B - 12 TB usage from JDC-KC overwritten by the 3 TB usage from JDC-SF** 
As with the previous example, only the last (similar) cloud storage value on the CSV is imported. This example also shows why these should be added together, since the client is storing data at both locations (this is a Partner with multiple sub-tenants). Ideally our storage locations would get their own metrics so that we could use different pricing for each location. Without that ability however, these values should at least be added together so that we have a way to bill for usage at all locations.

Client 2 usage shown on Acronis Cyber Cloud portal and CSV reports

- Totals [Total cloud storage size]: 14880.50 GB
- Totals [Partner-owned backup storage]: 0.00 GB 
- Local backup [Local backup]: 5563.22 GB 
- Cyber Protect [Backup storage (JDC-SF)]: 11837.33 GB
- Cyber Protect [Backup storage (JDC-KC)]: 3043.17 GB
- Cyber Backup [Backup storage (JDC-KC)]: 0.00 GB
- Cyber Backup [Backup storage (JDC-SF)]: 0.00 GB

Client 2 usage in WHMCS metrics (from v2.2.1-178 of this module)

- Cyber Protect Cloud - Cloud storage: 3043.17 GB
- Cyber Backup Cloud - Cloud storage: 0.00 GB
- Cyber Backup Cloud - Partner storage: 0.00 GB
- Cyber Backup Cloud - Local storage: 0.00 GB

Client 2 usage in WHMCS metrics (generated after fix 55f55dc)

- Cyber Protect Cloud - Cloud storage: 14880.50 GB
- Cyber Backup Cloud - Cloud storage: 0.00 GB
- Cyber Backup Cloud - Partner storage: 0.00 GB
- Cyber Backup Cloud - Local storage: 0.00 GB

**Comment by JOEsDC-Seth** [comment]
**Example C - partner storage is counted as cloud storage and overwrites both JDC-KC and JDC-SF**
For the last example, we have a partner account that hosts their own storage on-site and uses both of our cloud storage locations. Here we see that the partner storage is initially the only thing being counted as "Cloud storage" by the module. Applying fix 55f55dc adds in our cloud storage locations, however the partner storage is also counted in this total. I have now added a061e9e to address this issue.

Client 3 usage shown on Acronis Cyber Cloud portal and CSV reports

- Totals [Total cloud storage size]: 25233.98 GB
- Totals [Partner-owned backup storage]: 14260.16 GB
- Local backup [Local backup]: 8027.08 GB
- Cyber Protect [Backup storage (JDC-KC)]: 3043.17 GB
- Cyber Protect [Backup storage (JDC-SF)]: 7930.65 GB
- Cyber Backup [Backup storage (JDC-KC)]: 0.00 GB
- Cyber Backup [Backup storage (JDC-SF)]: 0.00 GB

Client 3 usage in WHMCS metrics (from v2.2.1-178 of this module)

- Cyber Protect Cloud - Cloud storage: 14260.16 GB
- Cyber Backup Cloud - Cloud storage: 0.00 GB
- Cyber Backup Cloud - Partner storage: 0.00 GB
- Cyber Backup Cloud - Local storage: 0.00 GB

Client 3 usage in WHMCS metrics (generated after fix 55f55dc)

- Cyber Protect Cloud - Cloud storage: 25233.98 GB
- Cyber Backup Cloud - Cloud storage: 0.00 GB
- Cyber Backup Cloud - Partner storage: 0.00 GB
- Cyber Backup Cloud - Local storage: 0.00 GB

Client 3 usage in WHMCS metrics (generated after fix a061e9e)

- Cyber Protect Cloud - Cloud storage: 10973.82 GB
- Cyber Backup Cloud - Cloud storage: 0.00 GB
- Cyber Backup Cloud - Partner storage: 14260.16 GB
- Cyber Backup Cloud - Local storage: 0.00 GB

**Comment by JOEsDC-Seth** [comment]
I do apologize for the large amount of info above. This was a bit difficult to illustrate due to the complexity of the issue. One final note: there are still a few discrepancies in the examples above that I would like some clarification on. First, local storage does not appear to be getting counted by the module. Perhaps this due to the fact that the usage I based these examples on was all for "Cyber Protect Cloud" (per workload) and not "Cyber Backup Cloud" (per GB). This leads me to the second question, which is why "Cyber Backup Cloud" has usage metrics for Partner storage and Local storage but "Cyber Backup Cloud" does not. Thanks!

**Comment by georgetasioulis** [comment]
JDC-* are your own backup locations (I assume based on Cyber Infrastructure Cluster), not Acronis hosted, right?
So "Cloud storage" is considered our own Cyber Infrastructure Cluster(s), while "Partner storage" is when we create a Partner account under our SP account, who then uses their own storage. 
OK this was something that had me confused until now. I thought "Partner storage" was our own storage (as in we are Acronis' partners running our own storage)

Based on the above, I want to confirm that by applying your two fixes, my storage metrics for customers both with Acronis hosted storage (per GB), as well as hosted on our own storage (per workload), show up correctly.

**Comment by JOEsDC-Seth** [comment]
Yes, that is correct: JDC-* are the Cyber Infrastructure clusters that we host. It is my understanding that "Cloud Storage" is anything stored within your own Cyber Infrastructure cluster(s) and (not Acronis hosted). If one of your client's also hosts their own Cyber Infrastructure cluster, it should then show up as "Partner Storage".

During CSV import, the module currently classifies any storage without an infrastructure back-end type (Acronis, Google, or Azure) as "Cloud Storage". a061e9e just adds one additional check: if the infrastructure owner ID matches the tenant ID for a "Cloud Storage" row, import it as "Partner Storage" (per GB, since there is not a per workload metric for this).

On applying these fixes... the storage metrics should be counted correctly for both Acronis hosted storage and your own storage after these changes. I am still uncertain about there only being a per GB metric for Partner and Local storage, although the licensing model is probably irrelevant for these two storage types.

**Comment by merx3** [comment]
Hi Seth,

Thank you very much for the info you shared. That helped us to reproduce and make a fix for the assinment of storage.

Pllease, check with the latest build (200). Now, partner owned and Acronis hosted storages should be correctly assigned to the appropriate metric. But if you still see an issue, please share with us. Right now, the metrics code should be aware of which infrastructure is partner owned and will re-assign the used storage(s) appropriately.

**Comment by JOEsDC-Seth** [comment]
Hi Marian,

I appreciate the quick turnaround on the update to build 200. I do see that multiple storage locations of the same type are now being added together as expected and our partners who host their own storage are getting counted correctly now. There still appears to be an issue with the usage calculation however, as the storage we provide to our clients is now getting added to "Partner Storage" instead of "Cloud Storage". The Acronis Cyber Cloud web interface is correctly distinguishing between these storage types as shown in the examples above.

/includes/acroniscloud/lib/Service/UsageReport/MetricsFetcher.php:116
In version 2.2.2-200, "Partner Storage" is now identified by checking the "platform_owned" attribute on each storage infrastructure. When I perform similar '/infra' API calls manually, the platform_owned attribute is only set on Acronis, Google, and Azure owned storage locations. Should this attribute be set for the storage we provide to our clients? If yes, I can open a support ticket to investigate why that attribute isn't currently set correctly. If no, then there no longer appears to be any type of storage that will be classified as "Cloud Storage" after upgrading to 2.2.2-200.

**Comment by merx3** [comment]
Hi Seth,

So, from what I understand, you have configured in cloud your own (not-Acronis-hosted) Cyber infrastructure (the JDC-* ones), that you then provide to your clients. Those clients, on their end, can have their own Cyber infras (which you can see in their partner tenant, in the Acronis cloud management console UI) hosted on their own cluster.

Now, to clear a misunderstanding. 
>  It is my understanding that "Cloud Storage" is anything stored within your own Cyber Infrastructure cluster (not Acronis hosted).
Not quite so. "Cloud Storage" is all storage that is platform owned, i.e. hosted on Acronis side. If you check the /infra API call again, you'll notice that your root tenant's id (the login info you use to connect to the Acronis Cloud server in WHMCS -> Servers) is aslo the tenant id shown on the infras that you have (property is "owner_tenant_id"), and your clients' infras have their own tenant's id set for them. They all are not hosted on Acronis premise, so they all have platform_owned: false, which makes them "Partner Storage", and not "Cloud Storage".

With that said, if you want to request a feature change in the addon module, where our per workload "Cloud Storage", for example (offering item: pw_storage), which includes our "Cyber Protect Cloud": Acronis, Azure, Google and Cloud (Acronis Servers) Hosted Storages, to also include your root tenant's (the one used to connect to Acronis API, in Servers) partner owned storage, then you have a mixed up logic, where the platform and non-platform storages are treated as Cloud Storage. And how will that work if you add a new Server in WHMCS with your client's credentials? Then his storage would also be considered as "Cloud Storage" for his sub-clients' orders. But we could provide another flag in our config file to enable this feature change, if this makes sense to do. From my perspective, however, this is mixing of storage types and could make the usage reports in billing metrics even more confusing. 

A second option, as you said, would be to change the JDC-* infras to be flagged as platform owned. As far as I'm aware, that would be an integrity violation, so it's not allowed. I'll check again with cloud team, but most likely that won't be a posibility.

I'd say the best solution on our side would be to implement a flag that would allow the root tenant infras to be treated as platform owned, which would group that infra's storage together with the Acronis-hosted storages. But again, that would contradict the actual logic and will force mixing of platform and partner (root tenant's) storages for all orders when that flag is enabled. If this feature makes sense to you, please make a feature request with your requirements and we'll investigate on a solution.

BR,
Marian
